### ISSUE TITLE
Placement issue - data? or control?

### ISSUE THREAD

**Issue by AlanElliott82** [rogerhyam/wfo-backbone-ui#10]
Globba sect. Ceratanthera (Horan.) Petersen [https://list.worldfloraonline.org/rhakhis/ui/#wfo-3500004002] trying to raise to accepted within.. [https://list.worldfloraonline.org/rhakhis/ui/#wfo-3500001115] Globba subgen. Ceratanthera (Horan.) K.J.Williams, but the only options are Globba the genus and Globba subgen. Globba. 

[https://list.worldfloraonline.org/rhakhis/ui/#wfo-3500001115] Globba subgen. Ceratanthera (Horan.) K.J.Williams is visible as an accepted name under globba.

**Comment by rogerhyam** [comment]
Logic bug in code as it was only returning possible parents with the right nameString not those with the right nameString OR genusString (in the case of subgenera and sections etc).

**Comment by rogerhyam** [comment]
Change on site and I've made the move of the section.
