### ISSUE TITLE
Use correct subgenus abbreviation

### ISSUE THREAD

**Issue by amueller-bgbm** [rogerhyam/wfo-backbone-ui#112]
ICNAFP defines the correct abbreviation for subgenus names in [Art. 5.1 Recommendation 5A](https://www.iapt-taxon.org/nomen/pages/main/art_5.html)
The correct abbreviation is "subg.". However, WFO/Rhakis currently uses "subgen.", which is incorrect.  

Also the parser/matcher should be adapted accordingly. E.g. when trying to check if a new name exists already on https://list.worldfloraonline.org/rhakhis/ui/index.html#add _Cicerbita_ **subgen.** _Poicilachena_ is currently recognized as an existing name but _Cicerbita_ **subg.** _Poicilachena_ is not.

**Comment by rogerhyam** [comment]
Thanks for pointing this out. I love the way the code throws in a random exception to a rule at the end of an example with no explanation as to why subgenus is different!

I've made some changes to the ranks table to accommodate this. I have also added a new display page to show the current ranks in the system. Here it is on the staging server. 

https://rhakhis.rbge.info/ranks.php

It isn't in production yet but I'll roll it onto the live server if this doesn't break anything. If you could test on the staging server for now that would be helpful.

You'll see there is an AKA field. I use any variant of the rank name (full name, abbreviation and AKA) for matching and import. We can add variants to the AKA field as they are required  - so long as they are not ambiguous between ranks!

I'll close this for now. Please re-open if you continue to have issues.
