### ISSUE TITLE
Batch process script for batches of new names

### ISSUE THREAD

**Issue by AlanElliott82** [rogerhyam/wfo-backbone-ui#28]
For batch processor, when I know I have big list of new names just run it.

**Comment by rogerhyam** [comment]
I've added this to the  matching functionality. You can opt to auto create a name. It is dependent on a few things:

- It won't do it if there are any homonyms for the name, they have to be done through the UI.
- You have to choose to be in unattended mode.
- You can't have homonyms OK ticked
- You have to specify the column with the rank in. This is so the name is created at a reasonable rank and leads on to the issue or "what if the rank in the data isn't recognised by Rhakhis. I've implemented a rank mapping/reconciling function further on in the process that can be done. 

This is on the sandbox but not main server yet as we should do some testing.
