### ISSUE TITLE
Batch name create Unrecognised Rank issue

### ISSUE THREAD

**Issue by AlanElliott82** [rogerhyam/wfo-backbone-ui#37]
822: Cattleya nothosect. Lawrenceya Van den Berg
Duplicates count: 0
Homonym count: 0
Candidate count: 0
No duplicates or homonyms and auto create is on so will try and auto create name.

Array ( [0] => Cattleya [1] => nothosect. [2] => Lawrenceya )
Can't create name because of unrecognized rank value: ""

Can work it in manually and start it running again, but would be good if it could juts skip it. 
ipni2019Issue table in sandbox

**Comment by AlanElliott82** [comment]
4647: subtrib. Anthelepidinae R.L.Barrett
Duplicates count: 0
Homonym count: 0
Candidate count: 0
No duplicates or homonyms and auto create is on so will try and auto create name.

Array ( [0] => subtrib. [1] => Anthelepidinae )
Can't create name because of unrecognized rank value: "subtribe - too many parts in the name for this rank"

Same thing with this.

**Comment by AlanElliott82** [comment]
295: Solanum virgatum [infrasp.unranked] albiflorum Hassk.
Duplicates count: 0
Homonym count: 0
Candidate count: 0

No duplicates or homonyms and auto create is on so will try and auto create name.

Array ( [0] => Solanum [1] => virgatum [2] => infrasp.unranked [3] => albiflorum )
Can't create name because of unrecognized rank value: ""

**Comment by rogerhyam** [comment]
no longer stops. could be improved further with more AKA rank name variants added to ranks table.
