### ISSUE TITLE
Year not importing properly from IPNI.

### ISSUE THREAD

**Issue by AlanElliott82** [rogerhyam/wfo-backbone-ui#38]
IPNI 2022 import the year was not imported properly from the file.
It only seems to be the 2022. Which make me think I must have done something weird in the workflow steps.  2018,19,20,21 look like they all have year of publication in fine. Year published before 2022, in the 2022 file I think are ok!

Here is the file.
[ipni2022new_nocary.export.csv.gz](https://github.com/rogerhyam/wfo-backbone-ui/files/9478344/ipni2022new_nocary.export.csv.gz)

**Comment by rogerhyam** [comment]
stupid hard coded year
