### ISSUE TITLE
Taxonomic status: some displaying incorrectly

### ISSUE THREAD

**Issue by AlanElliott82** [rogerhyam/wfo-backbone-ui#4]
subsection displaying as subSect. change to subsect.
proles displaying as prole. display as prol.
If species is a x then infraspecific taxon need to be displayed as nothosubsp. or nothovar.

**Comment by rogerhyam** [comment]
prole now abbreviated to prol.
subsection abbreviated to subsect.
Subspecific ranks of hybrid species now have notho added to the front of them.
(in next code update)
