### ISSUE TITLE
Large classifications - memory error

### ISSUE THREAD

**Issue by AlanElliott82** [rogerhyam/wfo-backbone-ui#44]
wfo_wcvp_fabaceae_2022_2_0_3 trying to generate the impact report. 

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 1310720 bytes) in /var/rhakhis/api/bulk/actions/impact_report.php on line 138

**Comment by rogerhyam** [comment]
Completely re-written importer so this should not happen. If it does it is another bug!
