### ISSUE TITLE
Data Issue. Autonym with authors

### ISSUE THREAD

**Issue by AlanElliott82** [rogerhyam/wfo-backbone-ui#6]
Autonyms with authors. e.g. (https://list.worldfloraonline.org/rhakhis/ui/#wfo-0001025731)
Causes the record not to behave as an autonym.

**Comment by rogerhyam** [comment]
I generated a list of the non deprecated autonyms with authors here:

[autonyms_with_authors.csv](https://github.com/rogerhyam/wfo-backbone-ui/files/8641159/autonyms_with_authors.csv)

there are 323 of them.

SQL for reference.

select i.`value`, n.rank, n.name_alpha, n.authors, if(tn.taxon_id, 'placed', 'unplaced'), if(t.taxon_name_id, 'accepted', 'synonym')
from `names` as n
join identifiers as i on n.prescribed_id = i.id
left join taxon_names as tn on tn.name_id = n.id
left join taxa as t on t.taxon_name_id = tn.id
where genus = `name` and length(authors) > 0 and `status` != 'deprecated';

**Comment by rogerhyam** [comment]
Is this still an issue now we are treating autonyms like normal names?

**Comment by AlanElliott82** [comment]
resolved a while ago
