### ISSUE TITLE
import author in bulk  "1Data too long for column 'change_log' at row 1Data too long for column"

### ISSUE THREAD

**Issue by AlanElliott82** [rogerhyam/wfo-backbone-ui#64]
Import author in batch issue working on Cupress.csv. Table in Sandbox.

as its running on once of the pages before refreshing this appears.

1Data too long for column 'change_log' at row 1Data too long for column 'change_log' at row 1Data too long for column 'change_log' at row 1Data too long for column 'change_log' at row 1Data too long for column 'change_log' at row 1Data too long for column 'change_log' at row 1Data too long for column 'change_log' at row 1Data too long for column

I'm not sure the authorships update even through the job runs to the end.

I dont see an issue with the data in the csv.
Curpess.csv. is in the sandbox.

**Comment by rogerhyam** [comment]
Should be fixed on live. Will migrate to sandbox tonight.
