### ISSUE TITLE
Batch precessor: Taxonomic references not being created for ranks above species

### ISSUE THREAD

**Issue by AlanElliott82** [rogerhyam/wfo-backbone-ui#74]
Adding taxonomic DB records to link out to powo in the batch processor. It seems to add to species and infraspecifics fine. I think it skips genera and above? The ability to add taxonomic (database?) references above rank of species would be useful. I hadn't noticed before if it was or wasn't taking. As many of the genera had existing links.

Its doesn't seem to have been added at all. Not just added and not linked. I tried adding the url manually to pull it in, not there.

wfo-4000000580 Adelonema has this https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:2668-1 in the spreadsheet.

wcvp_araceaace file if you need a file to test.

**Comment by AlanElliott82** [comment]
The example I gave. Has the taxonomic source ref with April 2023 comment. I wonder if something had not refreshed, or the page records cached. I looks to be ok. Lets close it.

**Comment by rogerhyam** [comment]
Try and do it again and then re-open.
